services:
    Akeneo\Tool\Bundle\ApiBundle\Command\CreateClientCommand:
        arguments:
            - '@akeneo_connectivity.connection.application.handler.create_connection'
        tags:
            - { name: console.command }

    Akeneo\Tool\Bundle\ApiBundle\Command\ListClientsCommand:
        arguments:
            - '@pim_api.repository.client'
        tags:
            - { name: console.command }
